services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-narrex}
    volumes:
      - pgdata:/var/lib/postgresql # correct for postgres:18
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  pgdata:
